
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


window = Tk()
window.title("Cat's Cradle")

window.geometry("800x500")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 500,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    20.0,
    20.0,
    580.0,
    370.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    612.0,
    20.0,
    777.0,
    370.0,
    fill="#D9D9D9",
    outline="")

button_image_1 = PhotoImage(
    file=Path("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=20.0,
    y=411.0,
    width=100.0,
    height=50.0
)

button_image_2 = PhotoImage(
    file=Path("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=152.0,
    y=411.0,
    width=100.0,
    height=50.0
)

button_image_3 = PhotoImage(
    file=Path("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=284.0,
    y=411.0,
    width=100.0,
    height=50.0
)

button_image_4 = PhotoImage(
    file=Path("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=416.0,
    y=411.0,
    width=100.0,
    height=50.0
)
window.resizable(False, False)
window.mainloop()
